spring:
  datasource:
    url: jdbc:mysql://rm-2vc1p30j19plo5421zo.mysql.cn-chengdu.rds.aliyuncs.com/online_site?characterEncoding=utf-8&useSSL=false
    username: root
    password: QWEr1223360222
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 设置邮箱主机
  mail:
    host: smtp.qq.com
    username: 1223360222@qq.com
    password: wmpqszdeiwtugjgj

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    cache: false




## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.online.site.start.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true